### ISSUE TITLE
Referencing related models

### ISSUE THREAD

**Issue by tomatohammado** [ellisonr/star-wars-helper#1]
https://github.com/ellisonr/star-wars-helper/blob/f507026edeb1e307e08c445ff9b3ccc5f840aba4/db/models/Character.js#L30-L32

Using `mongoose.Schema.Types.Mixed` is works in that it allows you to seed your models from the data from SWAPI. However, it does not work properly to related the field in Character back to the Planets model.

**Comment by ellisonr** [comment]
Finally figured out the seed. Took a lot of work, but the reference is now using ObjectId instead of Mixed.
