### ISSUE TITLE
Trying to get related Model data using `.populate`

### ISSUE THREAD

**Issue by tomatohammado** [ellisonr/star-wars-helper#2]
https://github.com/ellisonr/star-wars-helper/blob/f507026edeb1e307e08c445ff9b3ccc5f840aba4/controllers/characters.js#L6-L8

When refactoring your controller method to use the `.populate()` method from Mongoose, it could look something like this:

```js
Character.find({})
  .populate("home_planet")
  .exec((err, characters) => res.json(characters));
```

This does not work with how the Character model is defined using the `Mixed` type and not `ObjectId` for the `home_planet` field.

See: [Mongoose documentation: Population](https://mongoosejs.com/docs/populate.html#population)

**Comment by ellisonr** [comment]
Populate works now. It shows the name of the related starship and planet in the characters model. Used: 
`router.get("/", (req, res) => {
    Character.find({})
    .populate("home_planet", "name")
    .populate("starship", "name")
    .exec((err, characters) =>
    res.json(characters));
});`
