### ISSUE TITLE
Do not need the HTTP Method in the Path URI

### ISSUE THREAD

**Issue by tomatohammado** [ellisonr/star-wars-helper#3]
https://github.com/ellisonr/star-wars-helper/blob/f507026edeb1e307e08c445ff9b3ccc5f840aba4/controllers/characters.js#L25-L29

In RESTful architecture, you do not have `/create`, `/update/`, `/delete`  in the Path of the (controller) action. The HTTP method (`POST`, `PUT`, `DELETE`) contains that information, so your paths are generally just the resource (`/`) or the reference to a specific instance of that resource `/:id`

**Comment by ellisonr** [comment]
Fixed. I took out the /create for POST, the /update for PUT, and the /delete for DELETE. I also, took out the /name from /name/:name, but left the /id in /id/:id.

End results look like this:
router.get("/id/:id", (req,res) => {
router.get("/:name", (req, res) => {

router.post("/", (req,res) => {

router.put("/id/:id", (req, res) => {
router.put("/:name", (req, res) => {

router.delete("/id/:id", (req, res) => {
router.delete("/:name", (req, res) => {
